id: P008254
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13779
  title: རིག་ལམ་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    5f2a208026d34faa92af5ddce0cad04b:
      image_group_id: I1KG15277
      title: ''
      volume_number: 1
      total_pages: 214
