id: P008254
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:11:06.415883
source_metadata:
  id: bdr:W1KG13779
  title: རིག་ལམ་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    5f2a208026d34faa92af5ddce0cad04b:
      image_group_id: I1KG15277
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
