id: IAC31FF4F
legacy_id: P008254
ocr_import_info:
  bdrc_scan_id: W1KG13779
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:26:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:43:33.510697+00:00'
last_modified: 2022-08-31 14:43:41.642890
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13779
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13779
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིག་ལམ་ནོར་བུའི་ཕྲེང་བ།
  author: རིན་ཆེན་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9769130094802125
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG15277:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15277
      total_pages: 214
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15277.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9769130094802125
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
